<?php
// This file is generated by Webman, please don't modify it.

use support\Container;

if (!function_exists('container_get')) {
    /**
     * 从容器中获取实例（单例）
     * 
     * @param string $name 类名或接口名
     * @return mixed
     * 
     * @example
     * $foo = container_get(Foo::class);
     * $user_service = container_get(UserService::class);
     */
    function container_get(string $name)
    {
        return Container::get($name);
    }
}

if (!function_exists('container_make')) {
    /**
     * 从容器中创建新实例（每次创建新实例）
     * 
     * @param string $name 类名或接口名
     * @param array $parameters 构造函数参数
     * @return mixed
     * 
     * @example
     * $log_service = container_make(LogService::class, [$path, $name]);
     */
    function container_make(string $name, array $parameters = [])
    {
        return Container::make($name, $parameters);
    }
}

if (!function_exists('sys_config')) {
    /**
     * 获取系统配置项（带默认值）
     *
     * 读取来源：ma_system_config 表，通过 SystemConfigService + 缓存。
     *
     * @param string $key     配置键名（config_key）
     * @param mixed  $default 默认值（未配置或为 null 时返回）
     * @return mixed
     *
     * @example
     * $siteName = sys_config('site_name', 'MyPay');
     */
    function sys_config(string $key, mixed $default = null): mixed
    {
        /** @var \app\services\SystemConfigService $service */
        $service = Container::get(\app\services\SystemConfigService::class);
        return $service->getValue($key, $default);
    }
}
