<?php

// 支付中台菜单配置，菜单标题使用前端国际化 key 显示
return [
    'admin' => [
        [
            'id' => '01',
            'parentId' => '0',
            'path' => '/home',
            'name' => 'home',
            'component' => 'home/home',
            'meta' => [
                'title' => 'home',
                'hide' => false,
                'disable' => false,
                'keepAlive' => false,
                'affix' => true,
                'link' => '',
                'iframe' => false,
                'isFull' => false,
                'roles' => ['admin'],
                'svgIcon' => 'home',
                'icon' => '',
                'sort' => 1,
                'type' => 2,
            ],
        ],
        [
            'id' => '02',
            'parentId' => '0',
            'path' => '/merchant',
            'name' => 'merchantManagement',
            'meta' => [
                'title' => 'merchantManagement',
                'hide' => false,
                'disable' => false,
                'keepAlive' => true,
                'affix' => false,
                'link' => '',
                'iframe' => false,
                'isFull' => false,
                'roles' => ['admin'],
                'svgIcon' => 'classify',
                'icon' => '',
                'sort' => 2,
                'type' => 1,
            ],
        ],
        [
            'id' => '0201',
            'parentId' => '02',
            'path' => '/merchant/merchant-archive',
            'name' => 'merchantArchive',
            'component' => 'merchant/merchant-list/index',
            'meta' => [
                'title' => 'merchantArchive',
                'hide' => false,
                'disable' => false,
                'keepAlive' => true,
                'affix' => false,
                'link' => '',
                'iframe' => false,
                'isFull' => false,
                'roles' => ['admin'],
                'svgIcon' => 'classify',
                'icon' => '',
                'sort' => 1,
                'type' => 2,
            ],
        ],
        [
            'id' => '0202',
            'parentId' => '02',
            'path' => '/merchant/merchant-group',
            'name' => 'merchantGroup',
            'component' => 'merchant/merchant-group/index',
            'meta' => [
                'title' => 'merchantGroup',
                'hide' => false,
                'disable' => false,
                'keepAlive' => true,
                'affix' => false,
                'link' => '',
                'iframe' => false,
                'isFull' => false,
                'roles' => ['admin'],
                'svgIcon' => 'folder-menu',
                'icon' => '',
                'sort' => 2,
                'type' => 2,
            ],
        ],
        [
            'id' => '03',
            'parentId' => '0',
            'path' => '/channel',
            'name' => 'channelCenter',
            'meta' => [
                'title' => 'channelCenter',
                'hide' => false,
                'disable' => false,
                'keepAlive' => true,
                'affix' => false,
                'link' => '',
                'iframe' => false,
                'isFull' => false,
                'roles' => ['admin'],
                'svgIcon' => 'data-setting',
                'icon' => '',
                'sort' => 3,
                'type' => 1,
            ],
        ],
        [
            'id' => '0301',
            'parentId' => '03',
            'path' => '/channel/payment-method',
            'name' => 'paymentMethod',
            'component' => 'channel/payment-method/index',
            'meta' => [
                'title' => 'paymentMethod',
                'hide' => false,
                'disable' => false,
                'keepAlive' => true,
                'affix' => false,
                'link' => '',
                'iframe' => false,
                'isFull' => false,
                'roles' => ['admin'],
                'svgIcon' => 'data-setting',
                'icon' => '',
                'sort' => 1,
                'type' => 2,
            ],
        ],
        [
            'id' => '0302',
            'parentId' => '03',
            'path' => '/channel/payment-plugin',
            'name' => 'paymentPlugin',
            'component' => 'channel/payment-plugin/index',
            'meta' => [
                'title' => 'paymentPlugin',
                'hide' => false,
                'disable' => false,
                'keepAlive' => true,
                'affix' => false,
                'link' => '',
                'iframe' => false,
                'isFull' => false,
                'roles' => ['admin'],
                'svgIcon' => 'functions',
                'icon' => '',
                'sort' => 2,
                'type' => 2,
            ],
        ],
        [
            'id' => '0303',
            'parentId' => '03',
            'path' => '/channel/payment-plugin-config',
            'name' => 'paymentPluginConfig',
            'component' => 'channel/payment-plugin-conf/index',
            'meta' => [
                'title' => 'paymentPluginConfig',
                'hide' => false,
                'disable' => false,
                'keepAlive' => true,
                'affix' => false,
                'link' => '',
                'iframe' => false,
                'isFull' => false,
                'roles' => ['admin'],
                'svgIcon' => 'functions',
                'icon' => '',
                'sort' => 3,
                'type' => 2,
            ],
        ],
        [
            'id' => '0304',
            'parentId' => '03',
            'path' => '/channel/channel-list',
            'name' => 'channelList',
            'component' => 'channel/channel-list/index',
            'meta' => [
                'title' => 'channelList',
                'hide' => false,
                'disable' => false,
                'keepAlive' => true,
                'affix' => false,
                'link' => '',
                'iframe' => false,
                'isFull' => false,
                'roles' => ['admin'],
                'svgIcon' => 'data',
                'icon' => '',
                'sort' => 4,
                'type' => 2,
            ],
        ],
        [
            'id' => '0306',
            'parentId' => '03',
            'path' => '/channel/channel-monitor',
            'name' => 'channelDailyStat',
            'component' => 'channel/channel-daily-stat/index',
            'meta' => [
                'title' => 'channelDailyStat',
                'hide' => false,
                'disable' => false,
                'keepAlive' => true,
                'affix' => false,
                'link' => '',
                'iframe' => false,
                'isFull' => false,
                'roles' => ['admin'],
                'svgIcon' => 'safety',
                'icon' => '',
                'sort' => 6,
                'type' => 2,
            ],
        ],
        [
            'id' => '04',
            'parentId' => '0',
            'path' => '/route',
            'name' => 'routeCenter',
            'meta' => [
                'title' => 'routeCenter',
                'hide' => false,
                'disable' => false,
                'keepAlive' => true,
                'affix' => false,
                'link' => '',
                'iframe' => false,
                'isFull' => false,
                'roles' => ['admin'],
                'svgIcon' => 'switch',
                'icon' => '',
                'sort' => 4,
                'type' => 1,
            ],
        ],
        [
            'id' => '0401',
            'parentId' => '04',
            'path' => '/route/polling-group',
            'name' => 'pollingGroup',
            'component' => 'channel/polling-group/index',
            'meta' => [
                'title' => 'pollingGroup',
                'hide' => false,
                'disable' => false,
                'keepAlive' => true,
                'affix' => false,
                'link' => '',
                'iframe' => false,
                'isFull' => false,
                'roles' => ['admin'],
                'svgIcon' => 'switch',
                'icon' => '',
                'sort' => 1,
                'type' => 2,
            ],
        ],
        [
            'id' => '0402',
            'parentId' => '04',
            'path' => '/route/route-compile',
            'name' => 'routeCompile',
            'component' => 'route/route-compile/index',
            'meta' => [
                'title' => 'routeCompile',
                'hide' => false,
                'disable' => false,
                'keepAlive' => true,
                'affix' => false,
                'link' => '',
                'iframe' => false,
                'isFull' => false,
                'roles' => ['admin'],
                'svgIcon' => 'folder-menu',
                'icon' => '',
                'sort' => 2,
                'type' => 2,
            ],
        ],
        [
            'id' => '0403',
            'parentId' => '04',
            'path' => '/route/route-preview',
            'name' => 'routePreview',
            'component' => 'channel/route-preview/index',
            'meta' => [
                'title' => 'routePreview',
                'hide' => false,
                'disable' => false,
                'keepAlive' => true,
                'affix' => false,
                'link' => '',
                'iframe' => false,
                'isFull' => false,
                'roles' => ['admin'],
                'svgIcon' => 'switch',
                'icon' => '',
                'sort' => 3,
                'type' => 2,
            ],
        ],
        [
            'id' => '05',
            'parentId' => '0',
            'path' => '/transaction',
            'name' => 'transactionCenter',
            'meta' => [
                'title' => 'transactionCenter',
                'hide' => false,
                'disable' => false,
                'keepAlive' => true,
                'affix' => false,
                'link' => '',
                'iframe' => false,
                'isFull' => false,
                'roles' => ['admin'],
                'svgIcon' => 'table',
                'icon' => '',
                'sort' => 5,
                'type' => 1,
            ],
        ],
        [
            'id' => '0501',
            'parentId' => '05',
            'path' => '/transaction/pay-order',
            'name' => 'payOrder',
            'component' => 'transaction/pay-order/index',
            'meta' => [
                'title' => 'payOrder',
                'hide' => false,
                'disable' => false,
                'keepAlive' => true,
                'affix' => false,
                'link' => '',
                'iframe' => false,
                'isFull' => false,
                'roles' => ['admin'],
                'svgIcon' => 'table',
                'icon' => '',
                'sort' => 1,
                'type' => 2,
            ],
        ],
        [
            'id' => '0502',
            'parentId' => '05',
            'path' => '/transaction/refund-order',
            'name' => 'refundOrder',
            'component' => 'transaction/refund-order/index',
            'meta' => [
                'title' => 'refundOrder',
                'hide' => false,
                'disable' => false,
                'keepAlive' => true,
                'affix' => false,
                'link' => '',
                'iframe' => false,
                'isFull' => false,
                'roles' => ['admin'],
                'svgIcon' => 'switch',
                'icon' => '',
                'sort' => 2,
                'type' => 2,
            ],
        ],
        [
            'id' => '0503',
            'parentId' => '05',
            'path' => '/transaction/settlement-order',
            'name' => 'settlementOrder',
            'component' => 'transaction/settlement-order/index',
            'meta' => [
                'title' => 'settlementOrder',
                'hide' => false,
                'disable' => false,
                'keepAlive' => true,
                'affix' => false,
                'link' => '',
                'iframe' => false,
                'isFull' => false,
                'roles' => ['admin'],
                'svgIcon' => 'financial-statement',
                'icon' => '',
                'sort' => 3,
                'type' => 2,
            ],
        ],
        [
            'id' => '0504',
            'parentId' => '05',
            'path' => '/transaction/notify-log',
            'name' => 'channelNotifyLog',
            'component' => 'transaction/channel-notify-log/index',
            'meta' => [
                'title' => 'channelNotifyLog',
                'hide' => false,
                'disable' => false,
                'keepAlive' => true,
                'affix' => false,
                'link' => '',
                'iframe' => false,
                'isFull' => false,
                'roles' => ['admin'],
                'svgIcon' => 'more',
                'icon' => '',
                'sort' => 4,
                'type' => 2,
            ],
        ],
        [
            'id' => '0505',
            'parentId' => '05',
            'path' => '/transaction/callback-log',
            'name' => 'payCallbackLog',
            'component' => 'transaction/pay-callback-log/index',
            'meta' => [
                'title' => 'payCallbackLog',
                'hide' => false,
                'disable' => false,
                'keepAlive' => true,
                'affix' => false,
                'link' => '',
                'iframe' => false,
                'isFull' => false,
                'roles' => ['admin'],
                'svgIcon' => 'data-queries',
                'icon' => '',
                'sort' => 5,
                'type' => 2,
            ],
        ],
        [
            'id' => '06',
            'parentId' => '0',
            'path' => '/funds',
            'name' => 'fundsCenter',
            'meta' => [
                'title' => 'fundsCenter',
                'hide' => false,
                'disable' => false,
                'keepAlive' => true,
                'affix' => false,
                'link' => '',
                'iframe' => false,
                'isFull' => false,
                'roles' => ['admin'],
                'svgIcon' => 'financial-statement',
                'icon' => '',
                'sort' => 6,
                'type' => 1,
            ],
        ],
        [
            'id' => '0601',
            'parentId' => '06',
            'path' => '/funds/overview',
            'name' => 'fundsOverview',
            'component' => 'funds/overview/index',
            'meta' => [
                'title' => 'fundsOverview',
                'hide' => false,
                'disable' => false,
                'keepAlive' => true,
                'affix' => false,
                'link' => '',
                'iframe' => false,
                'isFull' => false,
                'roles' => ['admin'],
                'svgIcon' => 'financial-statement',
                'icon' => '',
                'sort' => 1,
                'type' => 2,
            ],
        ],
        [
            'id' => '0602',
            'parentId' => '06',
            'path' => '/funds/merchant-account',
            'name' => 'merchantAccount',
            'component' => 'funds/merchant-account/index',
            'meta' => [
                'title' => 'merchantAccount',
                'hide' => false,
                'disable' => false,
                'keepAlive' => true,
                'affix' => false,
                'link' => '',
                'iframe' => false,
                'isFull' => false,
                'roles' => ['admin'],
                'svgIcon' => 'balance-inquiry',
                'icon' => '',
                'sort' => 2,
                'type' => 2,
            ],
        ],
        [
            'id' => '0603',
            'parentId' => '06',
            'path' => '/funds/account-ledger',
            'name' => 'accountLedger',
            'component' => 'funds/account-ledger/index',
            'meta' => [
                'title' => 'accountLedger',
                'hide' => false,
                'disable' => false,
                'keepAlive' => true,
                'affix' => false,
                'link' => '',
                'iframe' => false,
                'isFull' => false,
                'roles' => ['admin'],
                'svgIcon' => 'data-analysis',
                'icon' => '',
                'sort' => 3,
                'type' => 2,
            ],
        ],
        [
            'id' => '07',
            'parentId' => '0',
            'path' => '/system',
            'name' => 'systemManagement',
            'meta' => [
                'title' => 'systemManagement',
                'hide' => false,
                'disable' => false,
                'keepAlive' => true,
                'affix' => false,
                'link' => '',
                'iframe' => false,
                'isFull' => false,
                'roles' => ['admin'],
                'svgIcon' => 'set',
                'icon' => '',
                'sort' => 7,
                'type' => 1,
            ],
        ],
        [
            'id' => '0701',
            'parentId' => '07',
            'path' => '/system/admin-user',
            'name' => 'adminUser',
            'component' => 'system/admin-user/index',
            'meta' => [
                'title' => 'adminUser',
                'hide' => false,
                'disable' => false,
                'keepAlive' => true,
                'affix' => false,
                'link' => '',
                'iframe' => false,
                'isFull' => false,
                'roles' => ['admin'],
                'svgIcon' => 'user',
                'icon' => '',
                'sort' => 1,
                'type' => 2,
            ],
        ],
        [
            'id' => '0702',
            'parentId' => '07',
            'path' => '/system/base-config',
            'name' => 'systemConfig',
            'component' => 'system/system-config/index',
            'meta' => [
                'title' => 'systemConfig',
                'hide' => false,
                'disable' => false,
                'keepAlive' => true,
                'affix' => false,
                'link' => '',
                'iframe' => false,
                'isFull' => false,
                'roles' => ['admin'],
                'svgIcon' => 'set',
                'icon' => '',
                'sort' => 2,
                'type' => 2,
            ],
        ],
        [
            'id' => '0703',
            'parentId' => '07',
            'path' => '/system/userinfo',
            'name' => 'userinfo',
            'component' => 'system/login-auth/index',
            'meta' => [
                'title' => 'userinfo',
                'hide' => true,
                'disable' => false,
                'keepAlive' => true,
                'affix' => false,
                'link' => '',
                'iframe' => false,
                'isFull' => false,
                'roles' => ['admin'],
                'svgIcon' => 'user',
                'icon' => '',
                'sort' => 3,
                'type' => 2,
            ],
        ],
        [
            'id' => '0704',
            'parentId' => '07',
            'path' => '/system/file-management',
            'name' => 'fileManagement',
            'component' => 'system/fileManagement/index',
            'meta' => [
                'title' => 'fileManagement',
                'hide' => false,
                'disable' => false,
                'keepAlive' => true,
                'affix' => false,
                'link' => '',
                'iframe' => false,
                'isFull' => false,
                'roles' => ['admin'],
                'svgIcon' => 'folder-menu',
                'icon' => '',
                'sort' => 4,
                'type' => 2,
            ],
        ],
    ],
    'merchant' => [
        [
            'id' => '01',
            'parentId' => '0',
            'path' => '/home',
            'name' => 'home',
            'component' => 'home/home',
            'meta' => [
                'title' => 'home',
                'hide' => false,
                'disable' => false,
                'keepAlive' => false,
                'affix' => true,
                'link' => '',
                'iframe' => false,
                'isFull' => false,
                'roles' => ['common'],
                'svgIcon' => 'home',
                'icon' => '',
                'sort' => 1,
                'type' => 2,
            ],
        ],
        [
            'id' => '02',
            'parentId' => '0',
            'path' => '/channel',
            'name' => 'channelCenter',
            'meta' => [
                'title' => 'channelCenter',
                'hide' => false,
                'disable' => false,
                'keepAlive' => true,
                'affix' => false,
                'link' => '',
                'iframe' => false,
                'isFull' => false,
                'roles' => ['common'],
                'svgIcon' => 'data-setting',
                'icon' => '',
                'sort' => 2,
                'type' => 1,
            ],
        ],
        [
            'id' => '0201',
            'parentId' => '02',
            'path' => '/channel/my-channel',
            'name' => 'myChannel',
            'component' => 'channel/my-channel/index',
            'meta' => [
                'title' => 'myChannel',
                'hide' => false,
                'disable' => false,
                'keepAlive' => true,
                'affix' => false,
                'link' => '',
                'iframe' => false,
                'isFull' => false,
                'roles' => ['common'],
                'svgIcon' => 'data-setting',
                'icon' => '',
                'sort' => 1,
                'type' => 2,
            ],
        ],
        [
            'id' => '0202',
            'parentId' => '02',
            'path' => '/channel/route-preview',
            'name' => 'routePreview',
            'component' => 'merchant/route-preview/index',
            'meta' => [
                'title' => 'routePreview',
                'hide' => false,
                'disable' => false,
                'keepAlive' => true,
                'affix' => false,
                'link' => '',
                'iframe' => false,
                'isFull' => false,
                'roles' => ['common'],
                'svgIcon' => 'switch',
                'icon' => '',
                'sort' => 2,
                'type' => 2,
            ],
        ],
        [
            'id' => '0203',
            'parentId' => '02',
            'path' => '/channel/api-credential',
            'name' => 'apiCredential',
            'component' => 'merchant/api-credential/index',
            'meta' => [
                'title' => 'apiCredential',
                'hide' => false,
                'disable' => false,
                'keepAlive' => true,
                'affix' => false,
                'link' => '',
                'iframe' => false,
                'isFull' => false,
                'roles' => ['common'],
                'svgIcon' => 'lock-pwd',
                'icon' => '',
                'sort' => 3,
                'type' => 2,
            ],
        ],
        [
            'id' => '03',
            'parentId' => '0',
            'path' => '/transaction',
            'name' => 'transactionCenter',
            'meta' => [
                'title' => 'transactionCenter',
                'hide' => false,
                'disable' => false,
                'keepAlive' => true,
                'affix' => false,
                'link' => '',
                'iframe' => false,
                'isFull' => false,
                'roles' => ['common'],
                'svgIcon' => 'table',
                'icon' => '',
                'sort' => 3,
                'type' => 1,
            ],
        ],
        [
            'id' => '0301',
            'parentId' => '03',
            'path' => '/transaction/pay-order',
            'name' => 'payOrder',
            'component' => 'merchant/pay-order/index',
            'meta' => [
                'title' => 'payOrder',
                'hide' => false,
                'disable' => false,
                'keepAlive' => true,
                'affix' => false,
                'link' => '',
                'iframe' => false,
                'isFull' => false,
                'roles' => ['common'],
                'svgIcon' => 'table',
                'icon' => '',
                'sort' => 1,
                'type' => 2,
            ],
        ],
        [
            'id' => '0302',
            'parentId' => '03',
            'path' => '/transaction/refund-order',
            'name' => 'refundOrder',
            'component' => 'merchant/refund-order/index',
            'meta' => [
                'title' => 'refundOrder',
                'hide' => false,
                'disable' => false,
                'keepAlive' => true,
                'affix' => false,
                'link' => '',
                'iframe' => false,
                'isFull' => false,
                'roles' => ['common'],
                'svgIcon' => 'switch',
                'icon' => '',
                'sort' => 2,
                'type' => 2,
            ],
        ],
        [
            'id' => '0303',
            'parentId' => '03',
            'path' => '/transaction/settlement-record',
            'name' => 'settlementRecord',
            'component' => 'merchant/settlement-record/index',
            'meta' => [
                'title' => 'settlementRecord',
                'hide' => false,
                'disable' => false,
                'keepAlive' => true,
                'affix' => false,
                'link' => '',
                'iframe' => false,
                'isFull' => false,
                'roles' => ['common'],
                'svgIcon' => 'financial-statement',
                'icon' => '',
                'sort' => 3,
                'type' => 2,
            ],
        ],
        [
            'id' => '04',
            'parentId' => '0',
            'path' => '/funds',
            'name' => 'fundsCenter',
            'meta' => [
                'title' => 'fundsCenter',
                'hide' => false,
                'disable' => false,
                'keepAlive' => true,
                'affix' => false,
                'link' => '',
                'iframe' => false,
                'isFull' => false,
                'roles' => ['common'],
                'svgIcon' => 'financial-statement',
                'icon' => '',
                'sort' => 4,
                'type' => 1,
            ],
        ],
        [
            'id' => '0401',
            'parentId' => '04',
            'path' => '/funds/withdrawable-balance',
            'name' => 'withdrawableBalance',
            'component' => 'merchant/withdrawable-balance/index',
            'meta' => [
                'title' => 'withdrawableBalance',
                'hide' => false,
                'disable' => false,
                'keepAlive' => true,
                'affix' => false,
                'link' => '',
                'iframe' => false,
                'isFull' => false,
                'roles' => ['common'],
                'svgIcon' => 'balance-inquiry',
                'icon' => '',
                'sort' => 1,
                'type' => 2,
            ],
        ],
        [
            'id' => '0402',
            'parentId' => '04',
            'path' => '/funds/balance-flow',
            'name' => 'balanceFlow',
            'component' => 'merchant/balance-flow/index',
            'meta' => [
                'title' => 'balanceFlow',
                'hide' => false,
                'disable' => false,
                'keepAlive' => true,
                'affix' => false,
                'link' => '',
                'iframe' => false,
                'isFull' => false,
                'roles' => ['common'],
                'svgIcon' => 'data-analysis',
                'icon' => '',
                'sort' => 2,
                'type' => 2,
            ],
        ],
        [
            'id' => '05',
            'parentId' => '0',
            'path' => '/system',
            'name' => 'basicSettings',
            'meta' => [
                'title' => 'basicSettings',
                'hide' => false,
                'disable' => false,
                'keepAlive' => true,
                'affix' => false,
                'link' => '',
                'iframe' => false,
                'isFull' => false,
                'roles' => ['common'],
                'svgIcon' => 'set',
                'icon' => '',
                'sort' => 5,
                'type' => 1,
            ],
        ],
        [
            'id' => '0501',
            'parentId' => '05',
            'path' => '/system/merchant-info',
            'name' => 'merchantInfo',
            'component' => 'merchant/merchant-info/index',
            'meta' => [
                'title' => 'merchantInfo',
                'hide' => false,
                'disable' => false,
                'keepAlive' => true,
                'affix' => false,
                'link' => '',
                'iframe' => false,
                'isFull' => false,
                'roles' => ['common'],
                'svgIcon' => 'user',
                'icon' => '',
                'sort' => 1,
                'type' => 2,
            ],
        ],
        [
            'id' => '0502',
            'parentId' => '05',
            'path' => '/system/login-auth',
            'name' => 'loginAuth',
            'component' => 'merchant/login-auth/index',
            'meta' => [
                'title' => 'loginAuth',
                'hide' => false,
                'disable' => false,
                'keepAlive' => true,
                'affix' => false,
                'link' => '',
                'iframe' => false,
                'isFull' => false,
                'roles' => ['common'],
                'svgIcon' => 'lock-pwd',
                'icon' => '',
                'sort' => 2,
                'type' => 2,
            ],
        ],
        [
            'id' => '0503',
            'parentId' => '05',
            'path' => '/system/userinfo',
            'name' => 'userinfo',
            'component' => 'system/userinfo/userinfo',
            'meta' => [
                'title' => 'userinfo',
                'hide' => true,
                'disable' => false,
                'keepAlive' => true,
                'affix' => false,
                'link' => '',
                'iframe' => false,
                'isFull' => false,
                'roles' => ['common'],
                'svgIcon' => 'user',
                'icon' => '',
                'sort' => 3,
                'type' => 2,
            ],
        ],
    ],
];
